import type { Href } from "expo-router";
import { router, Stack } from "expo-router";
import { useEffect, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { DataSourceBanner } from "@/components/family/data-source-banner";
import { FamilyFlatList as FlatList } from "@/components/family/family-refresh-control";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { familyApi } from "@/lib/family/family-api-client";
import type { FamilyApiCommerceCustomerProjection, FamilyApiMembershipProjection } from "@/lib/family/family-api-projections";
import { useFamilyApiSession } from "@/lib/family/family-api-session";
import { useFamilyMobile } from "@/lib/family/family-state";

export default function OrdersAssetsScreen() {
  const colors = useColors(); const session = useFamilyApiSession(); const state = useFamilyMobile();
  const [commerce, setCommerce] = useState<FamilyApiCommerceCustomerProjection | null>(null); const [membership, setMembership] = useState<FamilyApiMembershipProjection | null>(null);
  useEffect(() => { if (session.status !== "connected" || !session.token || !session.selectedFamily) return; let active = true; Promise.all([familyApi.getCommerceCustomerProjection<FamilyApiCommerceCustomerProjection>(session.token, session.selectedFamily.family_id), familyApi.getMembershipCustomerProjection<FamilyApiMembershipProjection>(session.token, session.selectedFamily.family_id)]).then(([nextCommerce, nextMembership]) => { if (!active) return; setCommerce(nextCommerce); setMembership(nextMembership); }).catch(() => undefined); return () => { active = false; }; }, [session.selectedFamily, session.status, session.token]);
  const intents = commerce?.order_intents ?? []; const entitlements = commerce?.entitlements ?? []; const benefits = membership?.benefits ?? []; const localItems = state.commerceIntentDraft ? [{ id: state.commerceIntentDraft.id, title: state.commerceIntentDraft.productTitle, state: "已保存意向", tone: "#2563EB" }] : [];
  const assets = [...intents.map((item) => ({ id: item.order_intent_id, title: item.product_ref, state: item.status === "SUBMITTED" ? "已保存意向" : "草稿中", tone: "#2563EB" })), ...localItems].slice(0, 3);
  return <ScreenContainer edges={["left", "right", "bottom"]}><Stack.Screen options={{ headerShown: true, title: "订单与资产", headerBackTitle: "返回" }} /><FlatList data={assets} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><View style={[styles.summary, { backgroundColor: colors.surface, borderColor: colors.border }]}><Metric label="方案意向" value={String(intents.length + localItems.length)} /><Metric label="可用权益" value={String(entitlements.filter((item) => item.status === "AVAILABLE").length)} /><Metric label="成长积分" value={membership?.dev_points ? String(membership.dev_points.balance) : "—"} /><Metric label="课程资产" value={String(state.campCompletedDays.length)} /></View><DataSourceBanner /><Text style={[styles.sectionTitle, { color: colors.text }]}>家庭资产</Text></View>} renderItem={({ item }) => <View style={[styles.asset, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.assetIcon}><IconSymbol name="ticket.fill" size={25} color="#2563EB" /></View><View style={styles.assetCopy}><Text style={[styles.assetTitle, { color: colors.text }]}>{item.title}</Text><Text style={[styles.assetSub, { color: colors.muted }]}>来自家庭已保存的方案和权益记录</Text></View><Text style={[styles.assetState, { color: item.tone }]}>{item.state}</Text></View>} ListEmptyComponent={<View style={[styles.empty, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="wallet.fill" size={32} color={colors.muted} /><Text style={[styles.emptyTitle, { color: colors.text }]}>这里会慢慢汇集家庭资产</Text><Text style={[styles.emptyCopy, { color: colors.muted }]}>当家庭保存方案意向、获得权益或完成课程后，可以在这里统一回看。</Text></View>} ListFooterComponent={<View style={styles.footer}><View style={[styles.rights, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.rightsTitle, { color: colors.text }]}>权益中心</Text><View style={styles.rightsGrid}><Right label="会员权益" value={String(benefits.filter((item) => item.status === "AVAILABLE").length)} icon="crown.fill" /><Right label="方案意向" value={String(intents.length + localItems.length)} icon="cart.fill" /><Right label="成长报告" value={state.lastReceipt ? "可回看" : "等待行动"} icon="chart.bar.fill" /><Right label="邀请记录" value={state.invitationDraft ? "已保存" : "—"} icon="gift.fill" /></View></View><Pressable onPress={() => router.push("/ui/UI-18" as Href)} style={({ pressed }) => [styles.primary, pressed && styles.pressed]}><Text style={styles.primaryText}>查看会员中心</Text><IconSymbol name="chevron.right" size={18} color="#FFFFFF" /></Pressable><Text style={[styles.boundary, { color: colors.muted }]}>此页不会支付、核销、下载、导出或发送内容；资产仅供家庭私有回看。</Text></View>} /></ScreenContainer>;
}
function Metric({ label, value }: { label: string; value: string }) { return <View style={styles.metric}><Text style={styles.metricValue}>{value}</Text><Text style={styles.metricLabel}>{label}</Text></View>; }
function Right({ label, value, icon }: { label: string; value: string; icon: "crown.fill" | "cart.fill" | "chart.bar.fill" | "gift.fill" }) { return <View style={styles.right}><IconSymbol name={icon} size={23} color="#F28C45" /><Text style={styles.rightLabel}>{label}</Text><Text style={styles.rightValue}>{value}</Text></View>; }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 38, gap: 10 }, header: { gap: 12 }, summary: { minHeight: 102, borderWidth: 1, borderRadius: 20, flexDirection: "row", alignItems: "center", paddingVertical: 12 }, metric: { flex: 1, alignItems: "center", gap: 4 }, metricValue: { color: "#09295A", fontSize: 22, lineHeight: 28, fontWeight: "900" }, metricLabel: { color: "#5B7091", fontSize: 10, lineHeight: 14, textAlign: "center" }, sectionTitle: { fontSize: 17, lineHeight: 23, fontWeight: "900" }, asset: { minHeight: 76, borderWidth: 1, borderRadius: 18, padding: 13, flexDirection: "row", alignItems: "center", gap: 10, marginTop: 10 }, assetIcon: { width: 44, height: 44, borderRadius: 15, backgroundColor: "#EAF2FF", alignItems: "center", justifyContent: "center" }, assetCopy: { flex: 1, gap: 4 }, assetTitle: { fontSize: 14, lineHeight: 19, fontWeight: "900" }, assetSub: { fontSize: 11, lineHeight: 16 }, assetState: { fontSize: 11, fontWeight: "900" }, empty: { marginTop: 10, borderWidth: 1, borderRadius: 18, padding: 18, alignItems: "center", gap: 8 }, emptyTitle: { fontSize: 15, lineHeight: 21, fontWeight: "900" }, emptyCopy: { fontSize: 12, lineHeight: 18, textAlign: "center" }, footer: { gap: 12, paddingTop: 18 }, rights: { borderWidth: 1, borderRadius: 20, padding: 15, gap: 12 }, rightsTitle: { fontSize: 16, lineHeight: 22, fontWeight: "900" }, rightsGrid: { flexDirection: "row", justifyContent: "space-between" }, right: { flex: 1, alignItems: "center", gap: 4 }, rightLabel: { color: "#5B7091", fontSize: 10, lineHeight: 14, textAlign: "center" }, rightValue: { color: "#09295A", fontSize: 11, lineHeight: 15, fontWeight: "900", textAlign: "center" }, primary: { minHeight: 52, borderRadius: 16, backgroundColor: "#F28C45", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 }, primaryText: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" }, boundary: { fontSize: 11, lineHeight: 17, textAlign: "center" }, pressed: { opacity: 0.82, transform: [{ scale: 0.985 }] }, });
