import type { Href } from "expo-router";
import { router, Stack } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { DataSourceBanner } from "@/components/family/data-source-banner";
import { FamilyFlatList as FlatList } from "@/components/family/family-refresh-control";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { familyApi } from "@/lib/family/family-api-client";
import type { FamilyApiServiceCustomerProjection } from "@/lib/family/family-api-projections";
import { useFamilyApiSession } from "@/lib/family/family-api-session";
import { useFamilyMobile } from "@/lib/family/family-state";

const SUPPORTS = [
  { label: "成长顾问", icon: "person.crop.circle.fill" as const, target: "UI-24" },
  { label: "班主任陪跑", icon: "book.fill" as const, target: "UI-05" },
  { label: "小助手", icon: "message.fill" as const, target: "UI-10" },
  { label: "专家答疑", icon: "headphones.fill" as const, target: "UI-19" },
] as const;

export default function MyServicesScreen() {
  const colors = useColors(); const session = useFamilyApiSession(); const state = useFamilyMobile();
  const [customer, setCustomer] = useState<FamilyApiServiceCustomerProjection | null>(null);
  useEffect(() => { if (session.status !== "connected" || !session.token || !session.selectedFamily) return; let active = true; familyApi.getServiceCustomerProjection<FamilyApiServiceCustomerProjection>(session.token, session.selectedFamily.family_id).then((result) => { if (active) setCustomer(result); }).catch(() => undefined); return () => { active = false; }; }, [session.selectedFamily, session.status, session.token]);
  const taskItems = useMemo(() => [
    { id: "today", title: state.todayAction.title, detail: state.todayAction.status === "checked_in" ? "已留下家庭回看" : "今天可以尝试的一件小事", done: state.todayAction.status === "checked_in" },
    ...(state.campStarted ? [{ id: "camp", title: "21 天成长营", detail: `已完成 ${state.campCompletedDays.length} 个小结`, done: state.campCompletedDays.length > 0 }] : []),
    ...(customer?.bookings.slice(0, 2).map((item) => ({ id: item.booking_request_id, title: "家庭咨询意向", detail: item.status === "CONFIRMED" ? "等待家庭进一步确认" : "已保存时间偏好", done: item.status === "CONFIRMED" })) ?? []),
    ...(state.activityInterestDraft ? [{ id: state.activityInterestDraft.id, title: state.activityInterestDraft.activityTitle, detail: "已保存活动意向", done: false }] : []),
  ].slice(0, 4), [customer?.bookings, state.activityInterestDraft, state.campCompletedDays.length, state.campStarted, state.todayAction]);
  const currentProgress = state.campStarted ? Math.round((state.campCompletedDays.length / 21) * 100) : 0;
  return <ScreenContainer edges={["left", "right", "bottom"]}><Stack.Screen options={{ headerShown: true, title: "我的服务", headerBackTitle: "返回" }} /><FlatList data={taskItems} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><View style={styles.hero}><View><Text style={styles.heroTitle}>家庭成长计划</Text><Text style={styles.heroSub}>{state.campStarted ? "正在按自己的节奏陪伴" : "从今天的一件小事开始"}</Text></View><View style={styles.circle}><Text style={styles.circleValue}>{currentProgress}%</Text><Text style={styles.circleLabel}>过程进度</Text></View></View><View style={styles.progressPanel}><View style={styles.progressRow}><Text style={styles.progressLabel}>这段时间的行动</Text><Text style={styles.progressValue}>{taskItems.filter((item) => item.done).length}/{taskItems.length || 1}</Text></View><View style={styles.track}><View style={[styles.fill, { width: `${Math.max(5, currentProgress)}%` }]} /></View><Text style={styles.progressHint}>这是家庭自己选择的过程节奏，不用于比较或评价。</Text></View><DataSourceBanner /><View style={[styles.supportPanel, { backgroundColor: colors.surface, borderColor: colors.border }]}>{SUPPORTS.map((item) => <Pressable key={item.label} onPress={() => router.push(`/ui/${item.target}` as Href)} style={({ pressed }) => [styles.support, pressed && styles.pressed]}><View style={styles.supportIcon}><IconSymbol name={item.icon} size={24} color="#2563EB" /></View><Text style={[styles.supportText, { color: colors.text }]}>{item.label}</Text></Pressable>)}</View><Text style={[styles.sectionTitle, { color: colors.text }]}>这周可以回看的事项</Text></View>} renderItem={({ item }) => <View style={[styles.task, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.dot, { backgroundColor: item.done ? "#16866D" : "#2563EB" }]}>{item.done ? <IconSymbol name="checkmark.circle.fill" size={15} color="#FFFFFF" /> : null}</View><View style={styles.taskCopy}><Text style={[styles.taskTitle, { color: colors.text }]}>{item.title}</Text><Text style={[styles.taskDetail, { color: colors.muted }]}>{item.detail}</Text></View></View>} ListFooterComponent={<View style={styles.actions}><Pressable onPress={() => router.push("/ui/UI-04" as Href)} style={({ pressed }) => [styles.secondary, { borderColor: colors.tint }, pressed && styles.pressed]}><Text style={[styles.secondaryText, { color: colors.tint }]}>查看方案</Text></Pressable><Pressable onPress={() => router.push("/ui/UI-09" as Href)} style={({ pressed }) => [styles.primary, pressed && styles.pressed]}><Text style={styles.primaryText}>继续行动</Text></Pressable><Text style={[styles.boundary, { color: colors.muted }]}>服务状态来自同一家庭空间；此页面不会替家庭创建预约、联系专家或发送通知。</Text></View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 38, gap: 10 }, header: { gap: 12 }, hero: { minHeight: 132, borderTopLeftRadius: 22, borderTopRightRadius: 22, backgroundColor: "#2563EB", padding: 19, flexDirection: "row", alignItems: "center", justifyContent: "space-between" }, heroTitle: { color: "#FFFFFF", fontSize: 25, lineHeight: 32, fontWeight: "900" }, heroSub: { color: "#DCEBFF", fontSize: 13, lineHeight: 19, marginTop: 5 }, circle: { width: 78, height: 78, borderRadius: 39, borderWidth: 6, borderColor: "#E4F1FF", alignItems: "center", justifyContent: "center" }, circleValue: { color: "#FFFFFF", fontSize: 19, lineHeight: 24, fontWeight: "900" }, circleLabel: { color: "#DCEBFF", fontSize: 8, lineHeight: 12 }, progressPanel: { borderBottomLeftRadius: 22, borderBottomRightRadius: 22, backgroundColor: "#FFFFFF", padding: 16, gap: 8, borderWidth: 1, borderColor: "#DCE6F5" }, progressRow: { flexDirection: "row", justifyContent: "space-between" }, progressLabel: { color: "#09295A", fontSize: 14, fontWeight: "800" }, progressValue: { color: "#2563EB", fontSize: 17, fontWeight: "900" }, track: { height: 8, borderRadius: 5, backgroundColor: "#E2E8F0" }, fill: { height: 8, borderRadius: 5, backgroundColor: "#2563EB" }, progressHint: { color: "#5B7091", fontSize: 11, lineHeight: 16 }, supportPanel: { borderWidth: 1, borderRadius: 20, paddingVertical: 14, flexDirection: "row" }, support: { flex: 1, alignItems: "center", gap: 6 }, supportIcon: { width: 42, height: 42, borderRadius: 15, backgroundColor: "#EAF2FF", alignItems: "center", justifyContent: "center" }, supportText: { fontSize: 10, lineHeight: 14, fontWeight: "800", textAlign: "center" }, sectionTitle: { fontSize: 17, lineHeight: 23, fontWeight: "900", paddingTop: 3 }, task: { minHeight: 66, borderRadius: 16, borderWidth: 1, padding: 12, flexDirection: "row", alignItems: "center", gap: 10, marginTop: 10 }, dot: { width: 22, height: 22, borderRadius: 11, alignItems: "center", justifyContent: "center" }, taskCopy: { flex: 1, gap: 3 }, taskTitle: { fontSize: 14, lineHeight: 19, fontWeight: "800" }, taskDetail: { fontSize: 11, lineHeight: 16 }, actions: { flexDirection: "row", gap: 10, flexWrap: "wrap", paddingTop: 18 }, secondary: { flex: 1, minHeight: 50, borderWidth: 1.5, borderRadius: 16, alignItems: "center", justifyContent: "center" }, primary: { flex: 1, minHeight: 50, borderRadius: 16, backgroundColor: "#2563EB", alignItems: "center", justifyContent: "center" }, secondaryText: { fontSize: 15, fontWeight: "900" }, primaryText: { color: "#FFFFFF", fontSize: 15, fontWeight: "900" }, boundary: { width: "100%", fontSize: 11, lineHeight: 17, textAlign: "center" }, pressed: { opacity: 0.82, transform: [{ scale: 0.985 }] }, });
