import type { Href } from "expo-router";
import { router, Stack } from "expo-router";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { DataSourceBanner } from "@/components/family/data-source-banner";
import { FamilyFlatList as FlatList } from "@/components/family/family-refresh-control";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { GROWTH_FOCUSES } from "@/lib/family/core-growth";
import { useFamilyApiSession } from "@/lib/family/family-api-session";
import { useFamilyMobile } from "@/lib/family/family-state";

export default function FamilyProfileScreen() {
  const colors = useColors(); const session = useFamilyApiSession(); const state = useFamilyMobile();
  const focus = GROWTH_FOCUSES.find((item) => item.id === state.selectedGrowthFocus);
  const timeline = [
    ...(state.selectedGrowthFocus ? [{ id: "focus", title: "选择了一个家庭关注方向", detail: focus?.title ?? "当前成长重点" }] : []),
    ...(state.lastReceipt ? [{ id: "action", title: "留下了一次家庭行动回看", detail: "这是一段家庭视角，不用证明效果。" }] : []),
    ...(state.campStarted ? [{ id: "camp", title: "开始了 21 天成长营", detail: `已完成 ${state.campCompletedDays.length} 个阶段小结。` }] : []),
    ...(state.consultationNeedDraft ? [{ id: "support", title: "保存了专家支持意向", detail: "还没有创建真实预约或外部联系。" }] : []),
  ];
  const profileCards = [
    { id: "report", label: "成长报告", detail: state.lastReceipt ? "可回看" : "等待行动", icon: "chart.bar.fill" as const, target: "UI-08" },
    { id: "plan", label: "90 天方案", detail: state.selectedGrowthFocus ? "已选择方向" : "从测评开始", icon: "book.fill" as const, target: "UI-04" },
    { id: "story", label: "成长记录", detail: state.privateGrowthStory ? "已保存" : "慢慢积累", icon: "checkmark.circle.fill" as const, target: "UI-12" },
    { id: "assessment", label: "测评回看", detail: Object.keys(state.assessmentAnswers).length ? "已开始" : "待选择", icon: "ticket.fill" as const, target: "UI-07" },
  ];
  return <ScreenContainer edges={["left", "right", "bottom"]}><Stack.Screen options={{ headerShown: true, title: "家庭档案", headerBackTitle: "返回" }} /><FlatList data={timeline} keyExtractor={(item) => item.id} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><View style={[styles.profileCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={styles.top}><View style={styles.avatar}><IconSymbol name="person.2.fill" size={39} color="#2563EB" /></View><View style={styles.copy}><Text style={[styles.name, { color: colors.text }]}>我们的家庭</Text><Text style={[styles.meta, { color: colors.muted }]}>家庭成员与成长过程只在这个家庭空间内回看</Text><Text style={[styles.role, { color: colors.tint }]}>{session.selectedFamily ? `当前角色：${session.selectedFamily.role}` : "家庭私有档案"}</Text></View></View><Text style={[styles.focusTitle, { color: colors.text }]}>当前想一起关注的事</Text><View style={styles.chips}>{(focus ? [focus.title] : ["亲子沟通", "学习习惯", "情绪陪伴"]).map((item) => <View key={item} style={styles.chip}><Text style={styles.chipText}>{item}</Text></View>)}</View></View><DataSourceBanner /><View style={styles.cards}>{profileCards.map((item) => <Pressable key={item.id} onPress={() => router.push(`/ui/${item.target}` as Href)} style={({ pressed }) => [styles.card, { backgroundColor: colors.surface, borderColor: colors.border }, pressed && styles.pressed]}><IconSymbol name={item.icon} size={26} color="#2563EB" /><View style={styles.cardCopy}><Text style={[styles.cardTitle, { color: colors.text }]}>{item.label}</Text><Text style={[styles.cardDetail, { color: colors.muted }]}>{item.detail}</Text></View></Pressable>)}</View><Text style={[styles.sectionTitle, { color: colors.text }]}>家庭成长时间线</Text></View>} renderItem={({ item }) => <View style={styles.timelineRow}><View style={styles.timelineRail}><View style={styles.timelineDot} /><View style={styles.timelineLine} /></View><View style={[styles.timelineCard, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.timelineTitle, { color: colors.text }]}>{item.title}</Text><Text style={[styles.timelineDetail, { color: colors.muted }]}>{item.detail}</Text></View></View>} ListEmptyComponent={<View style={[styles.empty, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.emptyTitle, { color: colors.text }]}>从一段家庭过程开始</Text><Text style={[styles.emptyCopy, { color: colors.muted }]}>选择一个关注方向、完成一次行动或保存一段小记后，这里会留下可回看的家庭过程。</Text></View>} ListFooterComponent={<View style={styles.footer}><Pressable onPress={() => router.push("/ui/UI-29" as Href)} style={({ pressed }) => [styles.primary, pressed && styles.pressed]}><Text style={styles.primaryText}>查看成长成果</Text><IconSymbol name="chevron.right" size={18} color="#FFFFFF" /></Pressable><Text style={[styles.boundary, { color: colors.muted }]}>家庭档案只展示当前家庭范围内的角色、同意与过程信息，不显示儿童身份资料、学校信息或诊断结论。</Text></View>} /></ScreenContainer>;
}
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 38, gap: 10 }, header: { gap: 12 }, profileCard: { borderWidth: 1, borderRadius: 20, padding: 15, gap: 13 }, top: { flexDirection: "row", gap: 12 }, avatar: { width: 60, height: 60, borderRadius: 22, backgroundColor: "#EAF2FF", alignItems: "center", justifyContent: "center" }, copy: { flex: 1, gap: 4 }, name: { fontSize: 21, lineHeight: 28, fontWeight: "900" }, meta: { fontSize: 11, lineHeight: 17 }, role: { fontSize: 11, lineHeight: 16, fontWeight: "800" }, focusTitle: { fontSize: 14, lineHeight: 20, fontWeight: "900" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 7 }, chip: { borderRadius: 12, backgroundColor: "#EAF2FF", paddingHorizontal: 10, paddingVertical: 6 }, chipText: { color: "#2563EB", fontSize: 11, fontWeight: "800" }, cards: { flexDirection: "row", flexWrap: "wrap", gap: 10 }, card: { width: "48.5%", minHeight: 94, borderWidth: 1, borderRadius: 17, padding: 12, gap: 8 }, cardCopy: { gap: 2 }, cardTitle: { fontSize: 13, lineHeight: 18, fontWeight: "900" }, cardDetail: { fontSize: 10, lineHeight: 15 }, sectionTitle: { fontSize: 17, lineHeight: 23, fontWeight: "900", paddingTop: 3 }, timelineRow: { flexDirection: "row", gap: 9, marginTop: 10 }, timelineRail: { width: 18, alignItems: "center" }, timelineDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: "#2563EB", marginTop: 16 }, timelineLine: { width: 2, flex: 1, backgroundColor: "#CFE1FF", marginTop: 3 }, timelineCard: { flex: 1, borderWidth: 1, borderRadius: 16, padding: 13, gap: 4 }, timelineTitle: { fontSize: 14, lineHeight: 19, fontWeight: "900" }, timelineDetail: { fontSize: 11, lineHeight: 17 }, empty: { marginTop: 10, borderWidth: 1, borderRadius: 18, padding: 16, gap: 6 }, emptyTitle: { fontSize: 15, lineHeight: 21, fontWeight: "900" }, emptyCopy: { fontSize: 12, lineHeight: 18 }, footer: { paddingTop: 18, gap: 10 }, primary: { minHeight: 52, borderRadius: 16, backgroundColor: "#2563EB", flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 }, primaryText: { color: "#FFFFFF", fontSize: 16, fontWeight: "900" }, boundary: { fontSize: 11, lineHeight: 17, textAlign: "center" }, pressed: { opacity: 0.82, transform: [{ scale: 0.985 }] }, });
