import type { Href } from "expo-router";
import { router, Stack } from "expo-router";
import { useEffect, useMemo, useState } from "react";
import { Pressable, StyleSheet, Text, View } from "react-native";
import { DataSourceBanner } from "@/components/family/data-source-banner";
import { FamilyFlatList as FlatList } from "@/components/family/family-refresh-control";
import { ScreenContainer } from "@/components/screen-container";
import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { familyApi } from "@/lib/family/family-api-client";
import type { FamilyApiServiceCustomerProjection } from "@/lib/family/family-api-projections";
import { useFamilyApiSession } from "@/lib/family/family-api-session";
import { useFamilyMobile } from "@/lib/family/family-state";

export default function ServiceRecordsScreen() {
  const colors = useColors(); const session = useFamilyApiSession(); const state = useFamilyMobile(); const [customer, setCustomer] = useState<FamilyApiServiceCustomerProjection | null>(null);
  useEffect(() => { if (session.status !== "connected" || !session.token || !session.selectedFamily) return; let active = true; familyApi.getServiceCustomerProjection<FamilyApiServiceCustomerProjection>(session.token, session.selectedFamily.family_id).then((result) => { if (active) setCustomer(result); }).catch(() => undefined); return () => { active = false; }; }, [session.selectedFamily, session.status, session.token]);
  const consultations = useMemo(() => [
    ...(customer?.bookings.map((item) => ({ id: item.booking_request_id, title: "家庭咨询意向", detail: `${channelLabel(item.channel)} · ${item.starts_at.slice(0, 10)}`, status: bookingLabel(item.status) })) ?? []),
    ...(state.consultationNeedDraft ? [{ id: state.consultationNeedDraft.id, title: state.consultationNeedDraft.offeringTitle, detail: "家庭私有咨询需求草稿", status: "已保存" }] : []),
  ].slice(0, 3), [customer?.bookings, state.consultationNeedDraft]);
  const activities = state.activityInterestDraft ? [{ id: state.activityInterestDraft.id, title: state.activityInterestDraft.activityTitle, detail: "家庭私有活动意向", status: "已保存" }] : [];
  const records = [...consultations.map((item) => ({ ...item, group: "咨询" })), ...activities.map((item) => ({ ...item, group: "活动" }))];
  return <ScreenContainer edges={["left", "right", "bottom"]}><Stack.Screen options={{ headerShown: true, title: "服务记录", headerBackTitle: "返回" }} /><FlatList data={records} keyExtractor={(item) => `${item.group}-${item.id}`} contentContainerStyle={styles.content} ListHeaderComponent={<View style={styles.header}><DataSourceBanner /><Text style={[styles.sectionTitle, { color: colors.text }]}>我的咨询</Text></View>} renderItem={({ item, index }) => <View>{index === consultations.length && activities.length ? <Text style={[styles.sectionTitle, { color: colors.text, marginTop: 16 }]}>我的活动</Text> : null}<View style={[styles.record, { backgroundColor: colors.surface, borderColor: colors.border }]}><View style={[styles.recordIcon, { backgroundColor: item.group === "咨询" ? "#EAF2FF" : "#E8F7F1" }]}><IconSymbol name={item.group === "咨询" ? "headphones.fill" : "calendar.fill"} size={24} color={item.group === "咨询" ? "#2563EB" : "#16866D"} /></View><View style={styles.recordCopy}><Text style={[styles.recordTitle, { color: colors.text }]}>{item.title}</Text><Text style={[styles.recordDetail, { color: colors.muted }]}>{item.detail}</Text></View><Text style={[styles.status, { color: item.status === "已保存" ? "#2563EB" : "#F28C45" }]}>{item.status}</Text></View></View>} ListEmptyComponent={<View style={[styles.empty, { backgroundColor: colors.surface, borderColor: colors.border }]}><IconSymbol name="calendar.fill" size={30} color={colors.muted} /><Text style={[styles.emptyTitle, { color: colors.text }]}>还没有需要回看的服务记录</Text><Text style={[styles.emptyCopy, { color: colors.muted }]}>保存一次咨询需求或活动意向后，这里会按家庭私有范围回看相应过程。</Text></View>} ListFooterComponent={<View style={styles.footer}><View style={[styles.support, { backgroundColor: colors.surface, borderColor: colors.border }]}><Text style={[styles.supportTitle, { color: colors.text }]}>服务支持</Text><View style={styles.supports}><Support icon="headphones.fill" label="服务说明" /><Support icon="message.fill" label="家庭反馈" /><Support icon="book.fill" label="常见问题" /></View></View><Pressable onPress={() => router.push("/ui/UI-31" as Href)} style={({ pressed }) => [styles.outlineButton, { borderColor: colors.tint }, pressed && styles.pressed]}><IconSymbol name="headphones.fill" size={20} color={colors.tint} /><Text style={[styles.outlineText, { color: colors.tint }]}>返回我的服务</Text></Pressable><Text style={[styles.boundary, { color: colors.muted }]}>服务记录用于回看安排、意向和家庭反馈，不代表服务结果；不会自动联系、拨号、发送消息或创建工单。</Text></View>} /></ScreenContainer>;
}
function Support({ icon, label }: { icon: "headphones.fill" | "message.fill" | "book.fill"; label: string }) { return <View style={styles.supportItem}><View style={styles.supportIcon}><IconSymbol name={icon} size={23} color="#2563EB" /></View><Text style={styles.supportLabel}>{label}</Text></View>; }
function channelLabel(channel: "VIDEO" | "TEXT" | "OFFLINE") { return channel === "VIDEO" ? "视频沟通" : channel === "TEXT" ? "文字沟通" : "线下活动"; }
function bookingLabel(status: string) { return status === "CONFIRMED" ? "待确认" : status === "CANCELLED" ? "已取消" : "已保存"; }
const styles = StyleSheet.create({ content: { padding: 16, paddingBottom: 38, gap: 10 }, header: { gap: 8 }, sectionTitle: { fontSize: 18, lineHeight: 24, fontWeight: "900" }, record: { minHeight: 76, borderWidth: 1, borderRadius: 18, padding: 12, flexDirection: "row", alignItems: "center", gap: 10, marginTop: 9 }, recordIcon: { width: 46, height: 46, borderRadius: 16, alignItems: "center", justifyContent: "center" }, recordCopy: { flex: 1, gap: 4 }, recordTitle: { fontSize: 14, lineHeight: 19, fontWeight: "900" }, recordDetail: { fontSize: 11, lineHeight: 16 }, status: { fontSize: 11, fontWeight: "900" }, empty: { marginTop: 10, borderWidth: 1, borderRadius: 18, padding: 18, gap: 8, alignItems: "center" }, emptyTitle: { fontSize: 15, lineHeight: 21, fontWeight: "900" }, emptyCopy: { fontSize: 12, lineHeight: 18, textAlign: "center" }, footer: { paddingTop: 18, gap: 12 }, support: { borderWidth: 1, borderRadius: 20, padding: 15, gap: 12 }, supportTitle: { fontSize: 16, lineHeight: 22, fontWeight: "900" }, supports: { flexDirection: "row", justifyContent: "space-around" }, supportItem: { alignItems: "center", gap: 5 }, supportIcon: { width: 42, height: 42, borderRadius: 15, backgroundColor: "#EAF2FF", alignItems: "center", justifyContent: "center" }, supportLabel: { color: "#5B7091", fontSize: 10, lineHeight: 14 }, outlineButton: { minHeight: 52, borderWidth: 1.5, borderRadius: 16, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6 }, outlineText: { fontSize: 15, fontWeight: "900" }, boundary: { fontSize: 11, lineHeight: 17, textAlign: "center" }, pressed: { opacity: 0.82, transform: [{ scale: 0.985 }] }, });
