"""Ports (interfaces) for the Product Intelligence domain — implemented by
`infrastructure/`. Per the four-layer rule in
`architecture/FAMILY_AI_PYTHON_ONLY_MIGRATION_PLAN_V1.md` section 3.

Scoped to the PR-001 acceptance chain (Override #6 item 2):
MarketSignal -> CustomerInsight -> Opportunity -> GrowthProblem ->
GrowthHypothesis -> GrowthStrategy -> ProductConcept. The remaining object
types in the instruction-01 list get simple load/save methods only; no
chain-traversal helper is provided for them yet.

PR-001R (chief-architect review on PR #27, item 3): every `load_*` method
now takes `tenant_scope` and MUST raise `ProductIntelligenceNotFoundError`
if the row exists but belongs to a different tenant — not a different
(existence-leaking) error. A caller cannot distinguish "wrong id" from
"right id, wrong tenant" by response shape.
"""
from __future__ import annotations

from typing import Protocol

from ..domain.entities import (
    ContradictionModel,
    CustomerInsight,
    CustomerSegment,
    Evidence,
    GrowthHypothesis,
    GrowthProblem,
    GrowthStrategy,
    MarketSignal,
    MarketTrend,
    Opportunity,
    ProductComponent,
    ProductConcept,
    ProductDefinition,
    ProductPattern,
    ProductZoneAssessment,
    ServiceBlueprintVersion,
    SignalCluster,
    UnmetNeed,
)


class ProductIntelligenceRepositoryPort(Protocol):
    async def save_market_signal(self, entity: MarketSignal) -> None: ...
    async def load_market_signal(self, entity_id: str, tenant_scope: str) -> MarketSignal: ...

    async def save_signal_cluster(self, entity: SignalCluster) -> None: ...
    async def save_market_trend(self, entity: MarketTrend) -> None: ...
    async def save_customer_segment(self, entity: CustomerSegment) -> None: ...
    async def save_evidence(self, entity: Evidence) -> None: ...

    async def save_customer_insight(self, entity: CustomerInsight) -> None: ...
    async def load_customer_insight(self, entity_id: str, tenant_scope: str) -> CustomerInsight: ...

    async def save_unmet_need(self, entity: UnmetNeed) -> None: ...

    async def save_opportunity(self, entity: Opportunity) -> None: ...
    async def load_opportunity(self, entity_id: str, tenant_scope: str) -> Opportunity: ...

    async def save_growth_problem(self, entity: GrowthProblem) -> None: ...
    async def load_growth_problem(self, entity_id: str, tenant_scope: str) -> GrowthProblem: ...

    async def save_growth_hypothesis(self, entity: GrowthHypothesis) -> None: ...
    async def load_growth_hypothesis(self, entity_id: str, tenant_scope: str) -> GrowthHypothesis: ...
    async def list_growth_hypotheses_by_problem(self, problem_id: str, tenant_scope: str) -> list[GrowthHypothesis]: ...

    async def save_contradiction_model(self, entity: ContradictionModel) -> None: ...

    async def save_growth_strategy(self, entity: GrowthStrategy) -> None: ...
    async def load_growth_strategy(self, entity_id: str, tenant_scope: str) -> GrowthStrategy: ...

    async def save_product_zone_assessment(self, entity: ProductZoneAssessment) -> None: ...

    async def save_product_concept(self, entity: ProductConcept) -> None: ...
    async def load_product_concept(self, entity_id: str, tenant_scope: str) -> ProductConcept: ...

    async def save_product_component(self, entity: ProductComponent) -> None: ...
    async def save_product_pattern(self, entity: ProductPattern) -> None: ...
    async def save_product_definition(self, entity: ProductDefinition) -> None: ...
    async def save_service_blueprint_version(self, entity: ServiceBlueprintVersion) -> None: ...
