"""PROVIDER_POLICY_RUNTIME 硬化(裁决 M3-MOS-CLOSEOUT-NEXT-001 Task B)。
governance/FPAI_PROVIDER_REGISTRY.yaml = 唯一 authoring SSOT。
从 YAML 生成【校验过的运行时策略产物 .ts】+ source_sha256(供 runtime 消费,不再手抄两份;.ts 会被 tsc 编译进 dist)。
- default: 生成 packages/principal-runtime/src/provider-registry.generated.ts
- --check: 重算 YAML sha256 与产物内 source_sha256 比对;不一致 → exit 1(CI drift guard:YAML 改而产物未重生成 = FAIL)
用法: python tools/build_provider_policy_snapshot.py [--check]
"""
from __future__ import annotations
import hashlib, json, re, sys
from pathlib import Path
import yaml

ROOT = Path(__file__).resolve().parents[1]           # 50_开发_dev
SRC = ROOT / "governance" / "FPAI_PROVIDER_REGISTRY.yaml"
OUT = ROOT / "packages" / "principal-runtime" / "src" / "provider-registry.generated.ts"


def yaml_sha256() -> str:
    return hashlib.sha256(SRC.read_bytes()).hexdigest()


def providers() -> list[dict]:
    doc = yaml.safe_load(SRC.read_text(encoding="utf-8")) or {}
    return [{
        "provider_id": p["provider_id"],
        "minor_data_allowed": bool(p.get("minor_data_allowed", False)),
        "private_text_allowed": bool(p.get("private_text_allowed", False)),
        "approved_environment": list(p.get("approved_environment", [])),
    } for p in doc.get("providers", [])]


def render() -> str:
    body = json.dumps(providers(), ensure_ascii=False, indent=2)
    return (
        "// GENERATED by tools/build_provider_policy_snapshot.py from governance/FPAI_PROVIDER_REGISTRY.yaml — DO NOT EDIT.\n"
        "// PROVIDER_POLICY_RUNTIME_001:Provider Registry = 唯一 SSOT;drift-guard 见 tools/build_provider_policy_snapshot.py --check。\n"
        f'export const PROVIDER_REGISTRY_SOURCE_SHA256 = "{yaml_sha256()}";\n'
        f"export const GENERATED_PROVIDERS = {body} as const;\n"
    )


def main() -> int:
    if "--check" in sys.argv:
        if not OUT.exists():
            print("DRIFT: generated artifact missing; run build_provider_policy_snapshot.py", file=sys.stderr)
            return 1
        m = re.search(r'PROVIDER_REGISTRY_SOURCE_SHA256 = "([0-9a-f]+)"', OUT.read_text(encoding="utf-8"))
        art = m.group(1) if m else ""
        cur = yaml_sha256()
        if art != cur:
            print(f"DRIFT: FPAI_PROVIDER_REGISTRY.yaml changed but generated artifact not regenerated.\n  yaml={cur}\n  artifact={art}", file=sys.stderr)
            return 1
        print("PROVIDER_POLICY SNAPSHOT DRIFT CHECK: PASS (source hash match)")
        return 0
    OUT.write_text(render(), encoding="utf-8")
    print(f"generated {OUT.name}  providers={len(providers())}  sha256={yaml_sha256()[:16]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
