export const FAMILY_PLATFORM_SIX_LOOP_SCENARIOS = Object.freeze([
  {
    id: 'LOOP-01',
    name: '家庭体检获客',
    uiScope: ['UI-01', 'UI-02'],
    input: 'family_entry',
    output: 'family_participation_and_read_projection',
    canonicalWrite: 'none_until_named_action',
    modelGateway: 'not_called',
    externalEffect: false,
  },
  {
    id: 'LOOP-02',
    name: 'AI诊断分析',
    uiScope: ['UI-03', 'UI-04'],
    input: 'family_perspective_and_evidence_boundary',
    output: 'synthetic_explanation_projection',
    canonicalWrite: 'no_diagnosis_no_outcome',
    modelGateway: 'no_op_or_rule_projection_only',
    externalEffect: false,
  },
  {
    id: 'LOOP-03',
    name: '每日任务执行',
    uiScope: ['UI-05', 'UI-09'],
    input: 'growth_plan_and_daily_task',
    output: 'action_checkin_and_next_hint',
    canonicalWrite: 'complete_growth_action',
    modelGateway: 'not_called',
    externalEffect: false,
  },
  {
    id: 'LOOP-04',
    name: '孩子端参与',
    uiScope: ['UI-07', 'UI-10'],
    input: 'family_shared_choice',
    output: 'child_participation_prompt',
    canonicalWrite: 'controlled_draft_or_named_action',
    modelGateway: 'no_op_or_rule_projection_only',
    externalEffect: false,
  },
  {
    id: 'LOOP-05',
    name: '榜单激励留存',
    uiScope: ['UI-11', 'UI-12', 'UI-29'],
    input: 'family_process_records',
    output: 'private_non_comparative_review',
    canonicalWrite: 'read_projection_only',
    modelGateway: 'not_called',
    externalEffect: false,
    forbidden: ['family_ranking', 'total_score', 'child_diagnosis'],
  },
  {
    id: 'LOOP-06',
    name: '报告分享裂变',
    uiScope: ['UI-25', 'UI-26', 'UI-28'],
    input: 'private_family_expression_draft',
    output: 'family_private_expression_note',
    canonicalWrite: 'controlled_draft_only',
    modelGateway: 'not_called',
    externalEffect: false,
    forbidden: ['public_publish', 'cross_family_visibility', 'external_share'],
  },
] as const);

export type FamilyPlatformSixLoopScenario = (typeof FAMILY_PLATFORM_SIX_LOOP_SCENARIOS)[number];
