// GENERATED by tools/build_provider_policy_snapshot.py from governance/FPAI_PROVIDER_REGISTRY.yaml — DO NOT EDIT.
// PROVIDER_POLICY_RUNTIME_001:Provider Registry = 唯一 SSOT;drift-guard 见 tools/build_provider_policy_snapshot.py --check。
export const PROVIDER_REGISTRY_SOURCE_SHA256 = "9b49a12d31d38932a8e5b34aff10ed00fb0f208a7369736fd738baf860246e13";
export const GENERATED_PROVIDERS = [
  {
    "provider_id": "anthropic-cc-switch",
    "minor_data_allowed": false,
    "private_text_allowed": false,
    "approved_environment": [
      "internal_livecheck",
      "model_first_internal"
    ]
  },
  {
    "provider_id": "zhipu-glm4v",
    "minor_data_allowed": false,
    "private_text_allowed": false,
    "approved_environment": [
      "internal_livecheck"
    ]
  }
] as const;
