import { useState } from "react";
import { ActivityIndicator, Modal, Pressable, StyleSheet, Text, View } from "react-native";

import { IconSymbol } from "@/components/ui/icon-symbol";
import { useColors } from "@/hooks/use-colors";
import { useFamilyMobile } from "@/lib/family/family-state";
import { getUiActionPolicy } from "@/lib/family/ui-action-policies";

export function PrivateAssetActions({ screenId, title }: { screenId: "UI-29" | "UI-30" | "UI-31" | "UI-32" | "UI-33" | "UI-34"; title: string }) {
  const colors = useColors(); const { recordUiAction } = useFamilyMobile();
  const [mode, setMode] = useState<"export" | "share" | null>(null); const [saving, setSaving] = useState(false);
  const policy = getUiActionPolicy(screenId) ?? { screenId, loop: "成长" as const, kind: "asset_export" as const, receiptMessage: "家庭资产操作已记录；未创建文件或外发内容。" };
  const confirm = () => { setSaving(true); setTimeout(() => { recordUiAction(policy, mode === "export" ? `查看${title}导出预览` : `记录${title}分享回执`); setSaving(false); }, 260); };
  return <><View style={styles.row}><Pressable onPress={() => setMode("export")} style={({ pressed }) => [styles.button, { borderColor: colors.tint }, pressed && styles.pressed]}><IconSymbol name="doc.text.fill" size={18} color={colors.tint} /><Text style={[styles.buttonText, { color: colors.tint }]}>导出预览</Text></Pressable><Pressable onPress={() => setMode("share")} style={({ pressed }) => [styles.button, { borderColor: colors.tint }, pressed && styles.pressed]}><IconSymbol name="square.and.arrow.up" size={18} color={colors.tint} /><Text style={[styles.buttonText, { color: colors.tint }]}>分享回执</Text></Pressable></View><Modal transparent visible={mode !== null} animationType="fade" onRequestClose={() => !saving && setMode(null)}><View style={styles.overlay}><View style={[styles.sheet, { backgroundColor: colors.background }]}><IconSymbol name={mode === "export" ? "doc.text.fill" : "square.and.arrow.up"} size={32} color={colors.tint} /><Text style={[styles.title, { color: colors.text }]}>{mode === "export" ? `${title}导出预览` : `${title}分享回执`}</Text><Text style={[styles.copy, { color: colors.muted }]}>{mode === "export" ? "将整理当前家庭范围内的过程摘要供你预览。本次不会创建文件、下载或导出数据。" : "将记录你希望分享该摘要的家庭私有回执。本次不会打开外部应用或发送任何内容。"}</Text><Pressable onPress={confirm} disabled={saving} style={({ pressed }) => [styles.primary, { backgroundColor: colors.tint }, pressed && !saving && styles.pressed]}>{saving ? <ActivityIndicator color="#FFFFFF" /> : <Text style={styles.primaryText}>确认并记录</Text>}</Pressable><Pressable onPress={() => setMode(null)} disabled={saving}><Text style={[styles.cancel, { color: colors.muted }]}>暂不操作</Text></Pressable></View></View></Modal></>;
}
const styles = StyleSheet.create({ row: { flexDirection: "row", gap: 10, marginTop: 12 }, button: { flex: 1, minHeight: 42, borderWidth: 1, borderRadius: 15, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 5 }, buttonText: { fontSize: 11, fontWeight: "900" }, overlay: { flex: 1, backgroundColor: "#09295A88", justifyContent: "flex-end", padding: 16 }, sheet: { borderRadius: 24, padding: 22, alignItems: "center", gap: 12 }, title: { fontSize: 18, lineHeight: 25, fontWeight: "900" }, copy: { fontSize: 12, lineHeight: 19, textAlign: "center" }, primary: { alignSelf: "stretch", minHeight: 48, borderRadius: 16, alignItems: "center", justifyContent: "center", marginTop: 3 }, primaryText: { color: "#FFFFFF", fontSize: 14, fontWeight: "900" }, cancel: { paddingTop: 4, fontSize: 12, fontWeight: "700" }, pressed: { opacity: 0.82, transform: [{ scale: 0.98 }] } });
