// @ts-nocheck
// Presentation-only shell; domain contracts remain type-checked in the existing adapters.
import { getScreensForNav, getWebScreen, WEB_PRIMARY_NAV, WEB_UI_SCREENS } from './web-ui-registry.js';

const escapeHtml = (value) => String(value ?? '').replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;').replaceAll("'", '&#039;');
const icon = (name) => `<span class="fai-icon" aria-hidden="true">${({ today: '⌂', growth: '↗', discover: '◎', services: '◇', mine: '○', search: '⌕', bell: '•', arrow: '→', shield: '✓', spark: '✦', chevron: '›' })[name] ?? '✦'}</span>`;
const FAMILY_TOPICS = ['亲子沟通', '学习习惯', '情绪支持', '家庭活动', '家长故事'];
const routeFromHash = () => { const route = window.location.hash.replace(/^#/, '').split('?')[0]; return route.startsWith('/') ? route : '/today'; };
const pageHeader = (screen) => `<header class="fai-page-head"><div><div class="fai-eyebrow"><span>${escapeHtml(screen.tab)}</span><i></i><span>${escapeHtml(screen.loop)}</span></div><h1>${escapeHtml(screen.title)}</h1><p>${escapeHtml(screen.subtitle)}</p></div><button class="fai-ghost-btn" type="button" data-open-all>${icon('spark')}<span>探索更多内容</span></button></header>`;
const primaryButton = (screen, label = screen.primaryAction) => screen.target ? `<button class="fai-primary-btn" type="button" data-screen-target="${screen.target}">${escapeHtml(label)} ${icon('arrow')}</button>` : `<button class="fai-primary-btn" type="button" data-feedback="这一步会保存在当前家庭空间">${escapeHtml(label)} ${icon('arrow')}</button>`;
const renderScreen = (screen) => {
  if (screen.template === 'home') return `${pageHeader(screen)}<section class="fai-hero fai-hero--home"><div><span class="fai-kicker">今晚一件事 · 约 8 分钟</span><h2>请先听完，再说你的看法</h2><p>今晚聊学校的事时，先用一句“我想听听你是怎么想的”开始。</p>${primaryButton(screen, '开始今晚的行动')}</div><strong>先连接<br>再建议</strong></section><section class="fai-grid fai-grid--recommendations"><article class="fai-card"><b>当前成长旅程</b><h3>第 2 周 · 家长先行动</h3><p>仅和自己过去比较；可以暂停、回顾和调整。</p></article><button class="fai-rec-card fai-rec-card--cyan" data-screen-target="UI-02"><b>整理当前最需要的家庭支持</b><small>不评分、不诊断</small>${icon('arrow')}</button><button class="fai-rec-card fai-rec-card--green" data-screen-target="UI-31"><b>查看已有课程、专家和活动安排</b><small>意向、确认与服务记录分开</small>${icon('arrow')}</button></section>`;
  if (screen.template === 'assessment') return `${pageHeader(screen)}<section class="fai-assessment-layout"><article class="fai-card fai-assessment-main"><span class="fai-kicker">家长视角 · 不自动成为孩子事实</span><h2>最近，你最想先理解哪个场景？</h2><div class="fai-choice-grid">${['亲子沟通','学习习惯','情绪调节','手机与边界','自我管理'].map((item, index) => `<button type="button" class="fai-choice ${index === 0 ? 'is-selected' : ''}" data-choice><b>${item}</b><small>从具体家庭情境开始</small></button>`).join('')}</div><div class="fai-form-actions"><button class="fai-text-btn" data-feedback="已保存为家庭私有草稿">稍后继续</button>${primaryButton(screen, '继续了解情境')}</div></article><aside class="fai-card fai-boundary-card"><h3>测评边界</h3><ul><li>整理家长当前观察</li><li>提出需要家庭确认的支持假设</li><li>不生成总分、排名或永久标签</li><li>不作医学或心理诊断</li></ul></aside></section>`;
  if (screen.template === 'interpretation') return `${pageHeader(screen)}<section class="fai-interpretation-hero"><div><span class="fai-kicker">家庭私有 · 假设不是事实</span><h2>先让对话重新变得安全</h2><p>这是可能的支持方向，需要家庭确认或驳回。</p></div><b>待确认</b></section><section class="fai-grid fai-grid--evidence">${[['观察来源','家长视角'],['支持假设','需家庭确认'],['仍然未知','需继续观察']].map(([title, state]) => `<article class="fai-card"><small>${title}</small><h3>当前仅作支持参考</h3><b>${state}</b></article>`).join('')}</section><section class="fai-card fai-next-step"><p>确认只建立成长意向，不代表已有成果，也不会自动购买服务。</p>${primaryButton(screen, '这个方向值得尝试')}</section>`;
  if (screen.template === 'plan' || screen.template === 'journey') return `${pageHeader(screen)}<section class="fai-plan-overview"><h2>从“急着给答案”到“先完整听见”</h2><p>方案是家庭确认后的可恢复计划，不是对家庭的评判。</p></section><section class="fai-stage-list">${['看见与理解','家长先行动','亲子共同练习','稳定与复盘'].map((title, index) => `<article class="fai-stage ${index === 1 ? 'is-current' : ''}"><b>0${index + 1}</b><h3>${title}</h3><p>每个阶段都可以暂停、回顾或调整。</p></article>`).join('')}</section>`;
  return `${pageHeader(screen)}<section class="fai-generic-hero"><div><span class="fai-kicker">家庭私有 · 可以慢慢来</span><h2>${escapeHtml(screen.subtitle)}</h2><p>从家里真实发生的小事开始，方便一起看见、商量和调整，不给任何人贴标签。</p>${primaryButton(screen)}</div><strong>${icon('spark')}</strong></section><section class="fai-grid fai-grid--generic">${screen.features.slice(0, 3).map((feature) => `<article class="fai-card"><small>今天的小方向</small><h3>${escapeHtml(feature)}</h3><p>从一个具体场景开始，随时可以暂停或回头看看。</p></article>`).join('')}</section>`;
};
const contextRail = (screen) => `<section class="fai-context-card"><b>陈家</b><small>当前家庭空间</small></section><section class="fai-context-card"><span>今天可以这样开始</span><h3>${screen.tab === 'services' ? '先聊聊，再决定要不要寻求帮助' : '先连接，再建议'}</h3><p>从家里真实发生的小事开始，尊重每个人的感受，也给彼此留下调整的空间。</p></section><section class="fai-context-card fai-trust-card">${icon('shield')}<div><b>家庭私有</b><p>内容只为当前家庭服务，可暂停、回顾和修改。</p></div></section>`;

export function createConsumerExperience(root, options = {}) {
  let currentScreen = getWebScreen(routeFromHash());
  let currentTopic = FAMILY_TOPICS[0];
  root.innerHTML = `<div class="family-web family-web--consumer"><aside class="fai-sidebar"><a class="fai-brand" href="#/today"><span>F</span><div><b>Family AI</b><small>家庭成长空间</small></div></a><nav class="fai-primary-nav">${WEB_PRIMARY_NAV.map((item) => `<button type="button" data-nav="${item.id}">${icon(item.id)}<span><b>${item.label}</b><small>${item.hint}</small></span></button>`).join('')}</nav><div class="fai-subnav" data-subnav></div><footer><button data-open-all>${icon('spark')}<span>探索更多内容</span></button><a href="?product=console">${icon('services')}<span>运营工作台</span></a></footer></aside><section class="fai-app-column"><header class="fai-topbar"><label class="fai-search">${icon('search')}<input type="search" placeholder="搜索家庭小记和成长内容" data-global-search></label><div class="fai-top-actions"><span class="fai-preview-state">家庭空间</span><button data-feedback="暂无新的家庭通知">${icon('bell')}</button></div></header><main class="fai-content" data-page-content></main></section><aside class="fai-context-rail" data-context-rail></aside><nav class="fai-mobile-nav">${WEB_PRIMARY_NAV.map((item) => `<button type="button" data-nav="${item.id}">${icon(item.id)}<span>${item.label}</span></button>`).join('')}</nav><div class="fai-toast" data-toast role="status"></div><div class="fai-overlay" data-all-overlay hidden><button data-close-all>关闭</button><section><h2>探索更多家庭成长内容</h2><div data-screen-results></div></section></div></div>`;
  const page = root.querySelector('[data-page-content]'); const subnav = root.querySelector('[data-subnav]'); const context = root.querySelector('[data-context-rail]'); const toast = root.querySelector('[data-toast]'); const overlay = root.querySelector('[data-all-overlay]');
  const showToast = (message) => { toast.textContent = message ?? ''; toast.classList.add('is-visible'); window.setTimeout(() => toast.classList.remove('is-visible'), 2000); };
  const navigate = (value) => { currentScreen = getWebScreen(value ?? 'UI-01'); if (window.location.hash !== `#${currentScreen.route}`) window.location.hash = currentScreen.route; render(); };
  const bind = () => { root.querySelectorAll('[data-screen-target]').forEach((button) => button.addEventListener('click', () => { overlay.hidden = true; navigate(button.dataset.screenTarget); })); root.querySelectorAll('[data-nav]').forEach((button) => button.addEventListener('click', () => { const first = getScreensForNav(button.dataset.nav)[0]; if (first) navigate(first.id); })); root.querySelectorAll('[data-topic]').forEach((button) => button.addEventListener('click', () => { currentTopic = button.dataset.topic; render(); showToast(`已切换到「${currentTopic}」`); })); root.querySelectorAll('[data-feedback]').forEach((button) => button.addEventListener('click', () => showToast(button.dataset.feedback))); root.querySelectorAll('[data-choice]').forEach((choice) => choice.addEventListener('click', () => { choice.parentElement.querySelectorAll('[data-choice]').forEach((item) => item.classList.remove('is-selected')); choice.classList.add('is-selected'); })); root.querySelectorAll('[data-open-all]').forEach((button) => button.addEventListener('click', () => { overlay.hidden = false; overlay.querySelector('[data-screen-results]').innerHTML = WEB_UI_SCREENS.map((screen) => `<button data-screen-target="${screen.id}">${escapeHtml(screen.title)}</button>`).join(''); bind(); })); root.querySelectorAll('[data-close-all]').forEach((button) => button.addEventListener('click', () => { overlay.hidden = true; })); };
  const render = () => { page.innerHTML = `<nav class="fai-topic-nav" aria-label="成长主题"><span>正在浏览</span>${FAMILY_TOPICS.map((topic) => `<button type="button" data-topic="${escapeHtml(topic)}" class="${topic === currentTopic ? 'is-active' : ''}">${escapeHtml(topic)}</button>`).join('')}</nav>${renderScreen(currentScreen)}`; context.innerHTML = contextRail(currentScreen); subnav.innerHTML = `<span>${escapeHtml(currentScreen.tab)}</span>${getScreensForNav(currentScreen.tab).map((screen) => `<button data-screen-target="${screen.id}" class="${screen.id === currentScreen.id ? 'is-active' : ''}">${escapeHtml(screen.title)}</button>`).join('')}`; root.querySelectorAll('[data-nav]').forEach((button) => button.classList.toggle('is-active', button.dataset.nav === currentScreen.tab)); document.title = `${currentScreen.title} · Family AI`; bind(); };
  const onHashChange = () => { currentScreen = getWebScreen(routeFromHash()); render(); }; window.addEventListener('hashchange', onHashChange); const globalSearch = root.querySelector('[data-global-search]'); if (globalSearch) globalSearch.addEventListener('focus', () => { overlay.hidden = false; }); render(); root.dataset.clientSurface = 'consumer-web-v2'; root.dataset.uiBaseline = String(WEB_UI_SCREENS.length); return { navigate, getCurrentScreen: () => currentScreen, destroy: () => window.removeEventListener('hashchange', onHashChange) };
}
