packages:
  - "apps/*"
  - "packages/*"
  - "products/we-are-family/apps/*"
  - "legacy-system/apps/*"
  - "legacy-system/contracts"
allowBuilds:
  esbuild: true
  sharp: true
  unrs-resolver: true
onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
publicHoistPattern:
  - "*babel*"
  - "@babel/*"
